### PR TITLE
Replace deprecated String.each with .each_line

### LINKED ISSUE #2: str.each has been depricated in ruby 1.9.x
In wpcapify line 63  <code>f.each do |l|</code>  which doesn't work in the latest version of ruby (1.9.1) as it has been depricated. Swapping with .each_char or .each_line works (but not being a ruby expert I am not sure if that's the correct way of doing it). 

Please fix. Cheers, 

Andrew

### PR DESCRIPTION
**Pull request by davidbenton**
fixes #2

### CODE REVIEW

**Comment by mallorydxw** [comment]
Thanks for the patch, but we're no longer maintaining this project (or even using capistrano). Feel free to maintain your own fork though.

**Comment by davidbenton** [comment]
Thanks. I thought as much, given the last commit date, but it was such a simple change... If it's permanently broken or not recommended, why not just delete the repo?

I got here from a [StackExchange answer](http://wordpress.stackexchange.com/a/659/50131) and would be interested in a follow up on your workflow and deployment methods. As a dev who only occasionally uses WP, it seems there's not a community consensus. Your old workflow appealed to me, so the current probably would as well. I'm sure you're busy with actual work, but just thought I'd mention it.

**Comment by mallorydxw** [comment]
> If it's permanently broken or not recommended, why not just delete the repo?

We have no use for it anymore, but that doesn't make it useless. If Capistrano is somebody's preferred method of deployment then this project may have some use to them.

I will look into putting a notice on our older projects though, when I have the time, so that it's more obvious that they're no longer maintained.

>  Your old workflow appealed to me, so the current probably would as well.

That may not be true. Our needs and capabilities have changed a lot since we were using Capistrano.

But to answer your question, we use [chef](https://github.com/chef/chef) now.

**Comment by davidbenton** [comment]
Thanks, @tomdxw.

**Pull request closed without merging**
